# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b31be5c6d7fe08e11ebce5c8386dfe68"
application_url = "https://example.com"
embedded = true
name = "sample-data"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_publications,write_online_store_navigation,write_content,write_translations,write_locales"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
